# Generated by Django 6.0.1 on 2026-01-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=155)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('origem', models.CharField(blank=True, help_text='Origem do lançamento (ex.: GestãoClick, Manual)', max_length=50, null=True)),
                ('referencia_externa', models.CharField(blank=True, help_text='ID ou referência do sistema de origem', max_length=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
