# Generated by Django 6.0.1 on 2026-01-16 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_fornecedor'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_interno', models.CharField(max_length=50)),
                ('valor_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comissao_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de comissão', max_digits=5, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='empresas.empresa')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('empresa', 'codigo_interno')},
            },
        ),
    ]
