# Generated by Django 6.0.1 on 2026-01-16 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_orcamento_orcamentoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoitem',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoitem',
            name='desconto_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Desconto em %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orcamentoitem',
            name='desconto_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Desconto em valor fixo', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orcamentoitem',
            name='descricao',
            field=models.CharField(blank=True, help_text='Detalhes do serviço (ex: Limpeza de 4 splits)', max_length=255, null=True),
        ),
    ]
