# Generated by Django 6.0.1 on 2026-01-18 00:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_orcamentoitem_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='desconto_tipo',
            field=models.CharField(blank=True, choices=[('percentual', 'Percentual (%)'), ('valor', 'Valor (R$)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='desconto_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
