# Generated by Django 6.0.1 on 2026-01-18 01:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_orcamento_desconto_tipo_orcamento_desconto_valor'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('faturada', 'Faturada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='empresas.empresa')),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='clientes.orcamento')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
