# Generated by Django 6.0.1 on 2026-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='condicoes_pagamento',
            field=models.CharField(blank=True, help_text='Ex.: 3x sem juros, Entrada + 2 parcelas', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='observacoes_pagamento',
            field=models.TextField(blank=True, help_text='Observações sobre pagamento no orçamento', null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='tipo_pagamento',
            field=models.CharField(blank=True, choices=[('avista', 'À vista'), ('parcelado', 'Parcelado')], help_text='Forma de pagamento proposta ao cliente', max_length=20, null=True),
        ),
    ]
