# Generated by Django 6.0.1 on 2026-01-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_orcamento_condicoes_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='observacoes_pagamento',
            field=models.TextField(blank=True, help_text='Ex.: 50% entrada na confirmação do serviço', null=True),
        ),
    ]
