# Generated by Django 6.0.1 on 2026-01-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_orcamento_observacoes_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='condicoes_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='observacoes_pagamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_pagamento',
            field=models.CharField(blank=True, choices=[('avista', 'À vista'), ('parcelado', 'Parcelado')], max_length=20, null=True),
        ),
    ]
