# Generated by Django 6.0.1 on 2026-01-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_venda_condicoes_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número da parcela (1, 2, 3...)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('forma_pagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='clientes.venda')),
            ],
            options={
                'ordering': ['data_vencimento'],
            },
        ),
    ]
