# Generated by Django 6.0.1 on 2026-01-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_parcelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='observacoes_pagamento_real',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_pagamento_real',
            field=models.CharField(blank=True, choices=[('avista', 'À vista'), ('parcelado', 'Parcelado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_pagamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
