# Generated by Django 6.0.1 on 2026-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_venda_data_pagamento_venda_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
