# Generated by Django 6.0.1 on 2026-01-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_parcelamento_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status_financeiro',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Parcial'), ('quitada', 'Quitada')], default='aberta', max_length=10),
        ),
    ]
