# Generated by Django 6.0.1 on 2026-01-20 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_venda_status_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='orcamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venda', to='clientes.orcamento'),
        ),
    ]
