# Generated by Django 6.0.1 on 2026-01-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_venda_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status_financeiro',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Parcial'), ('quitada', 'Quitada'), ('em_atraso', 'Em atraso')], default='aberta', max_length=10),
        ),
    ]
