# Generated by Django 6.0.1 on 2026-01-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_alter_venda_status_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='status_cobranca',
            field=models.CharField(blank=True, choices=[('nao_enviado', 'Não enviado'), ('enviado', 'Enviado'), ('negociacao', 'Em negociação')], default='nao_enviado', max_length=20),
        ),
    ]
