# Generated by Django 6.0.1 on 2026-01-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_alter_orcamentoitem_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoitem',
            name='descricao',
            field=models.CharField(blank=True, default='', help_text='Detalhes do serviço (ex: Limpeza de 4 splits)', max_length=255),
        ),
    ]
